backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "contenido"
    label: "Contenido de la Web"
    files:
      - file: "index.html"
        label: "Información Principal"
        name: "index"
        fields:
          - { label: "Título Principal", name: "title", widget: "string" }
          - { label: "Fecha del Evento", name: "fecha", widget: "string" }
          - { label: "Lugar", name: "lugar", widget: "string" }
